#### HillaryEmails

In [163]:
import numpy as np
import pandas as pd
import re

In [164]:
#先看看数据
df = pd.read_csv('HillaryEmails.csv')
df.head()

Id  DocNumber                                    MetadataSubject  \
0   1  C05739545                                                WOW   
1   2  C05739546  H: LATEST: HOW SYRIA IS AIDING QADDAFI AND MOR...   
2   3  C05739547                                      CHRIS STEVENS   
3   4  C05739550                         CAIRO CONDEMNATION - FINAL   
4   5  C05739554  H: LATEST: HOW SYRIA IS AIDING QADDAFI AND MOR...   

     MetadataTo       MetadataFrom  SenderPersonId           MetadataDateSent  \
0             H  Sullivan, Jacob J            87.0  2012-09-12T04:00:00+00:00   
1             H                NaN             NaN  2011-03-03T05:00:00+00:00   
2            ;H    Mills, Cheryl D            32.0  2012-09-12T04:00:00+00:00   
3             H    Mills, Cheryl D            32.0  2012-09-12T04:00:00+00:00   
4  Abedin, Huma                  H            80.0  2011-03-11T05:00:00+00:00   

        MetadataDateReleased  \
0  2015-05-22T04:00:00+00:00   
1  2015-05-22T04:00:00+00:00   
2  2015-05-22T04:00:00+00:00   
3  2015-05-22T04:00:00+00:00   
4  2015-05-22T04:00:00+00:00   

                                     MetadataPdfLink MetadataCaseNumber  \
0  DOCUMENTS/HRC_Email_1_296/HRCH2/DOC_0C05739545...       F-2015-04841   
1  DOCUMENTS/HRC_Email_1_296/HRCH1/DOC_0C05739546...       F-2015-04841   
2  DOCUMENTS/HRC_Email_1_296/HRCH2/DOC_0C05739547...       F-2015-04841   
3  DOCUMENTS/HRC_Email_1_296/HRCH2/DOC_0C05739550...       F-2015-04841   
4  DOCUMENTS/HRC_Email_1_296/HRCH1/DOC_0C05739554...       F-2015-04841   

                         ...                         ExtractedTo  \
0                        ...                                 NaN   
1                        ...                                 NaN   
2                        ...                                  B6   
3                        ...                                 NaN   
4                        ...                                 NaN   

                              ExtractedFrom         ExtractedCc  \
0  Sullivan, Jacob J <Sullivan11@state.gov>                 NaN   
1                                       NaN                 NaN   
2       Mills, Cheryl D <MillsCD@state.gov>        Abedin, Huma   
3       Mills, Cheryl D <MillsCD@state.gov>  Mitchell, Andrew B   
4                                       NaN                 NaN   

                        ExtractedDateSent ExtractedCaseNumber  \
0  Wednesday, September 12, 2012 10:16 AM        F-2015-04841   
1                                     NaN        F-2015-04841   
2  Wednesday, September 12, 2012 11:52 AM        F-2015-04841   
3   Wednesday, September 12,2012 12:44 PM        F-2015-04841   
4                                     NaN        F-2015-04841   

  ExtractedDocNumber ExtractedDateReleased ExtractedReleaseInPartOrFull  \
0          C05739545            05/13/2015              RELEASE IN FULL   
1          C05739546            05/13/2015              RELEASE IN PART   
2          C05739547            05/14/2015              RELEASE IN PART   
3          C05739550            05/13/2015              RELEASE IN PART   
4          C05739554            05/13/2015              RELEASE IN PART   

                                   ExtractedBodyText  \
0                                                NaN   
1  B6\nThursday, March 3, 2011 9:45 PM\nH: Latest...   
2                                                Thx   
3                                                NaN   
4  H <hrod17@clintonemail.com>\nFriday, March 11,...   

                                             RawText  
0  UNCLASSIFIED\nU.S. Department of State\nCase N...  
1  UNCLASSIFIED\nU.S. Department of State\nCase N...  
2  UNCLASSIFIED\nU.S. Department of State\nCase N...  
3  UNCLASSIFIED\nU.S. Department of State\nCase N...  
4  B6\nUNCLASSIFIED\nU.S. Department of State\nCa...  

[5 rows x 22 columns]

In [165]:
#去掉id和extractedbodytext的缺省值
df = df[['Id','ExtractedBodyText']].dropna()

In [166]:
df[0:5].values

array([[2,
        'B6\nThursday, March 3, 2011 9:45 PM\nH: Latest How Syria is aiding Qaddafi and more... Sid\nhrc memo syria aiding libya 030311.docx; hrc memo syria aiding libya 030311.docx\nMarch 3, 2011\nFor: Hillary'],
       [3, 'Thx'],
       [5,
        'H <hrod17@clintonemail.com>\nFriday, March 11, 2011 1:36 PM\nHuma Abedin\nFw: H: Latest: How Syria is aiding Qaddafi and more... Sid\nhrc memo syria aiding libya 030311.docx\nPis print.'],
       [6,
        "Pis print.\n-•-...-^\nH < hrod17@clintonernailcom>\nWednesday, September 12, 2012 2:11 PM\n°Russorv@state.gov'\nFw: Meet The Right-Wing Extremist Behind Anti-fvluslim Film That Sparked Deadly Riots\nFrom [meat)\nSent: Wednesday, September 12, 2012 01:00 PM\nTo: 11\nSubject: Meet The Right Wing Extremist Behind Anti-Muslim Film That Sparked Deadly Riots\nhtte/maxbiumenthal.com12012/09/meet-the-right-wing-extremist-behind-anti-musiim-tihn-that-sparked-\ndeadly-riots/\nSent from my Verizon Wireless 4G LTE DROID\nU.S. Departm

In [167]:
#数据清洗
def clean_email_text(text):
    text = text.replace('\n',' ') #str.replace(old, new[, max])把字符串中的 old（旧字符串） 替换成 new(新字符串)
    text = re.sub(r'-',' ',text) #re.sub的函数原型为：re.sub(pattern, repl, string, count=0)替换字符串中的匹配项,repl表示替换后的
    text = re.sub(r'\d+/\d+/\d+',"",text)  #匹配日期格式
    text = re.sub(r'[0-2]?[0-9]:[0-6][0-9]',"",text)  #匹配时刻格式
    text = re.sub(r"[\w]+@[\.\w]+","",text)  #匹配邮件格式
    text = re.sub(r"/[a-zA-Z]*[:\//\]*[A-Za-z0-9\-_]+\.+[A-Za-z0-9\.\/%&=\?\-_]+/i","",text)  #匹配网址格式
    pure_text = ''  #防止还有其他特殊字符，loop一遍过滤
    for letter in text:
        if letter.isalpha() or letter == ' ':  #str.isalpha()如果字符串至少有一个字符并且所有字符都是字母则返回 True,否则返回 False
            pure_text += letter
    text = ' '.join(word for word in pure_text.split() if len(word)>1)    
    return text

In [168]:
#看下清洗后的数据
docs = df['ExtractedBodyText']
docs = docs.apply(lambda s:clean_email_text(s))
docs.head(1).values

array(['Thursday March PM Latest How Syria is aiding Qaddafi and more Sid hrc memo syria aiding libya docx hrc memo syria aiding libya docx March For Hillary'],
      dtype=object)

In [169]:
#建立一个内容列表
doclist = docs.values
doclist

array(['Thursday March PM Latest How Syria is aiding Qaddafi and more Sid hrc memo syria aiding libya docx hrc memo syria aiding libya docx March For Hillary',
       'Thx',
       'Friday March PM Huma Abedin Fw Latest How Syria is aiding Qaddafi and more Sid hrc memo syria aiding libya docx Pis print',
       ...,
       'Big change of plans in the Senate Senator Reid just announced that he was no longer going to move forward with the omnibus appropriations bill Instead he filed cloture motions on the repeal of Dont Ask Dont Tell and the DREAM Act Those petitions will ripen on Saturday So it looks like the Senate will be again considering the new START Treaty tomorrow We should know the starting time shortly',
       'PVerveer Friday December AM From Please let me know if can be of any help to your department and will happy to do and please thank Mrs Hillary Clinton on behalf of me and supporting Afghan women Thank you',
       'See below'], dtype=object)

In [170]:
#导入gensim库进行LDA建模
from gensim import corpora,models,similarities
import gensim

In [171]:
import nltk
stoplist = nltk.corpus.stopwords.words('english')

In [172]:
#去除停用词
texts = [[word for word in doc.lower().split() if word not in stoplist] for doc in doclist]  

In [173]:
texts[0]

['thursday',
 'march',
 'pm',
 'latest',
 'syria',
 'aiding',
 'qaddafi',
 'sid',
 'hrc',
 'memo',
 'syria',
 'aiding',
 'libya',
 'docx',
 'hrc',
 'memo',
 'syria',
 'aiding',
 'libya',
 'docx',
 'march',
 'hillary']

In [174]:
#将单词转换为index
dictionary = corpora.Dictionary(texts)
corpus = [dictionary.doc2bow(text) for text in texts]

In [175]:
corpus[10]

[(5, 3),
 (6, 1),
 (8, 1),
 (9, 8),
 (14, 1),
 (20, 5),
 (23, 6),
 (24, 5),
 (25, 1),
 (26, 5),
 (27, 5),
 (29, 5),
 (30, 5),
 (31, 5),
 (35, 5),
 (37, 5),
 (39, 5),
 (44, 1),
 (45, 5),
 (46, 5),
 (47, 1),
 (49, 5),
 (50, 5),
 (54, 13),
 (55, 5),
 (57, 6),
 (59, 5),
 (69, 1),
 (70, 1),
 (71, 1),
 (72, 1),
 (73, 2),
 (74, 1),
 (75, 1),
 (76, 1),
 (77, 1),
 (78, 1),
 (79, 1),
 (80, 2),
 (81, 2),
 (82, 1),
 (83, 2),
 (84, 1),
 (85, 2),
 (86, 1),
 (87, 1),
 (88, 1),
 (89, 2),
 (90, 1),
 (91, 1),
 (92, 3),
 (93, 1),
 (94, 1),
 (95, 2),
 (96, 1),
 (97, 9),
 (98, 1),
 (99, 1),
 (100, 3),
 (101, 2),
 (102, 1),
 (103, 3),
 (104, 2),
 (105, 1),
 (106, 1),
 (107, 1),
 (108, 1),
 (109, 1),
 (110, 1),
 (111, 1),
 (112, 1),
 (113, 2),
 (114, 1),
 (115, 1),
 (116, 2),
 (117, 1),
 (118, 1),
 (119, 1),
 (120, 1),
 (121, 1),
 (122, 1),
 (123, 1),
 (124, 1),
 (125, 1),
 (126, 1),
 (127, 1),
 (128, 1),
 (129, 2),
 (130, 1),
 (131, 1),
 (132, 1),
 (133, 1),
 (134, 1),
 (135, 1),
 (136, 1),
 (137, 1),
 (138

In [176]:
#拟合lda模型
lda = gensim.models.ldamodel.LdaModel(corpus=corpus,id2word=dictionary,num_topics=20)
lda.print_topic(10,topn=5)  #打印第10号分类的前5个单词

'0.010*"party" + 0.006*"said" + 0.006*"new" + 0.005*"would" + 0.005*"president"'

In [177]:
lda.print_topics(num_topics = 20,num_words=5) #前20个主题的前5个单词

[(0,
  '0.009*"palin" + 0.008*"obama" + 0.005*"romney" + 0.004*"traffic" + 0.004*"argentina"'),
 (1,
  '0.017*"ok" + 0.005*"go" + 0.005*"negotiating" + 0.004*"dont" + 0.004*"would"'),
 (2,
  '0.007*"us" + 0.006*"know" + 0.004*"israel" + 0.004*"netanyahu" + 0.004*"get"'),
 (3,
  '0.012*"us" + 0.009*"state" + 0.006*"united" + 0.006*"said" + 0.005*"would"'),
 (4,
  '0.012*"pm" + 0.010*"thanks" + 0.009*"good" + 0.008*"thx" + 0.007*"like"'),
 (5,
  '0.039*"pm" + 0.015*"office" + 0.013*"room" + 0.013*"secretarys" + 0.012*"state"'),
 (6,
  '0.012*"yes" + 0.007*"development" + 0.007*"also" + 0.006*"work" + 0.006*"could"'),
 (7,
  '0.028*"pm" + 0.017*"call" + 0.015*"office" + 0.012*"email" + 0.011*"secretary"'),
 (8,
  '0.012*"doc" + 0.009*"strategic" + 0.008*"state" + 0.008*"house" + 0.006*"health"'),
 (9,
  '0.083*"pm" + 0.039*"office" + 0.036*"secretarys" + 0.026*"meeting" + 0.023*"room"'),
 (10,
  '0.010*"party" + 0.006*"said" + 0.006*"new" + 0.005*"would" + 0.005*"president"'),
 (11,
  '0.

### 作业：
![tupian](./作业.png)

In [350]:
new_email = pd.read_csv('new_hillary_email.txt',header=None,sep='\n')
l1 = np.arange(0,len(new_email[0])).reshape(-1,1)
new_email.insert(0,'id',l1)
# # new_email[:,'ExtractedBodyText']=new_email[:,0]
new_email.columns=['ID','ExtractedBodyText']
new_email.info()

#清洗数据
new_text = new_email['ExtractedBodyText'].apply(lambda s:clean_email_text(s))
new_text.head(1).values

new_lists = new_text.values
new_lower = [[word for word in doc.lower().split() if word not in stoplist] for doc in new_lists]
new_lower[0]
dictionary = corpora.Dictionary(new_lower)
corpus = [dictionary.doc2bow(text) for text in new_lower]
corpus[2]
print('得到topic为：',list(lda.get_document_topics(corpus[2])))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
ID                   15 non-null int32
ExtractedBodyText    15 non-null object
dtypes: int32(1), object(1)
memory usage: 260.0+ bytes
得到topic为： [(7, 0.28153357), (8, 0.63664824)]


#### 手撸Gibbs LDA

In [178]:
import numpy as np
import seaborn as sns
np.random.seed(0)

In [179]:
'''
词库里一共就五个单词V：money,loan,bank,river,stream
并且一共就两个话题T: T1, T2
假设此刻我们有两个『话题-文字』的分布为：
ϕ1money=1/3, ϕ1loan=1/3, ϕ1bank=1/3
ϕ2bank=1/3, ϕ2stream=1/3, ϕ2river=1/3
'''
vocab = ['money','loan','bank','river','stream']
z_1 = np.array([1/3,1/3,1/3,.0,.0])
z_2 = np.array([.0,.0,1/3,1/3,1/3])

In [180]:
#把两个topic分布转换为phi概率分布矩阵,这就是想要通过Gibbs学到的分布
phi_actual = np.array([z_1,z_2]).T.reshape(len(z_2),2)
phi_actual

array([[0.33333333, 0.        ],
       [0.33333333, 0.        ],
       [0.33333333, 0.33333333],
       [0.        , 0.33333333],
       [0.        , 0.33333333]])

In [181]:
D=16 #假定生成16个文档
mean_length = 10 #默认每个文档平均单词个数
len_doc = np.random.poisson(mean_length,size=D)  #随机生成泊松分布的句子长度
T = 2 

docs =[]
orig_topics = []
for i in range(D):
    z = np.random.randint(0,2)
    if z == 0:
        words = np.random.choice(vocab,size=(len_doc[i]),p=z_1).tolist() #按照p概率分布，从vocab中抽取泊松分布的个数的单词
    else:
        words = np.random.choice(vocab,size=(len_doc[i]),p=z_2).tolist()
    orig_topics.append(z)
    docs.append(words)

In [182]:
#打印两个看看文档
print(' '.join(docs[0]))
print(" ".join(docs[5]))

loan bank loan money money loan bank loan loan bank
river river bank stream river stream stream bank stream river stream river stream


In [183]:
orig_topics

[0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0]

In [184]:
#Gibbs初始化指针
w_i = []  #存储单词index列表
i = [] 
d_i = []  #存储文档index列表
z_i = []  #存储topic分布
counter = 0

for doc_idx,doc in enumerate(docs): #遍历文档  
    for word_idx,word in enumerate(doc):  #遍历文档中的单词
        #np.where(condiction,x,y)这个函数的三个输入参数分别是条件（可以是矩阵），x,y数值矩阵用于返回值的选取
        w_i.append(np.where(np.array(vocab)==word)[0][0])  #得到目前单词在vocab中的index
        i.append(counter) #记录下次数
        d_i.append(doc_idx) #记录下文档index
        z_i.append(np.random.randint(0,T))  #随机初始化topic分布
        counter += 1
        
#统一格式
w_i = np.array(w_i)
d_i = np.array(d_i)
z_i = np.array(z_i)

In [185]:
#初始化word_topic分布
WT = np.zeros((len(vocab),T))  #新建空矩阵
for idx,word_ in enumerate(vocab):
    topics = z_i[np.where(w_i==idx)]  #相当于给出数组的下标
    for t in range(T):
        WT[idx,t] = sum(topics==t) #统计两类topic出现次数

#同理初始化topic_doc分布  
DT = np.zeros((D,T))        
for idx,doc_ in enumerate(range(D)):
    topics = z_i[np.where(d_i==idx)]
    for t in range(T):
        DT[idx,t] = sum(topics==t)

In [186]:
#备份原始分布
WT_orig = WT.copy()
DT_orig = DT.copy()

In [187]:
DT

array([[ 8.,  2.],
       [ 6.,  5.],
       [ 3.,  6.],
       [ 5.,  4.],
       [ 8., 10.],
       [ 8.,  5.],
       [ 2.,  2.],
       [ 7.,  3.],
       [ 4.,  6.],
       [ 6.,  2.],
       [ 5.,  5.],
       [ 2.,  9.],
       [ 8.,  8.],
       [ 6.,  3.],
       [ 5.,  7.],
       [ 6.,  6.]])

In [188]:
WT

array([[11., 14.],
       [20.,  7.],
       [29., 28.],
       [11., 17.],
       [18., 17.]])

#### Gibbs采样
![gibbs](./Gibbs采样.png)

In [189]:
#Gibbs采样
phi_1 = np.zeros((len(vocab),100))
phi_2 = np.zeros((len(vocab),100)) #初始化采样记录phi

iters = 100

#使用的利克雷分布作为先验概率
beta = 1
alpha = 1

for step in range(iters):
    for current in i:
        #分别取出对应index的文档和单词，即D和W
        doc_idx = d_i[current]
        w_idx = w_i[current]
        
        #并将取出的从总集合中删去
        DT[doc_idx,z_i[current]] -= 1
        WT[w_idx,z_i[current]] -= 1
        
        #计算新的W和D分布
        prob_word = (WT[w_idx,:]+beta) / (WT[:,:].sum(axis=0)+len(vocab)*beta)
        prob_document = (DT[doc_idx,:]+alpha) / (DT.sum(axis=0)+D*alpha)
        prob = prob_word*prob_document #就是上面的公式
        
        #更新z值
        z_i[current] = np.random.choice([0,1],1,p=prob/prob.sum())[0]
        
        #更新计数器
        DT[doc_idx,z_i[current]] += 1
        WT[w_idx,z_i[current]] += 1
        
        #记录phi的变化
        phi = WT/(WT.sum(axis=0))
        phi_1[:,step] = phi[:,0]
        phi_2[:,step] = phi[:,1]

In [190]:
DT

array([[10.,  0.],
       [11.,  0.],
       [ 9.,  0.],
       [ 1.,  8.],
       [ 1., 17.],
       [ 0., 13.],
       [ 1.,  3.],
       [10.,  0.],
       [ 2.,  8.],
       [ 0.,  8.],
       [ 0., 10.],
       [ 1., 10.],
       [ 0., 16.],
       [ 9.,  0.],
       [12.,  0.],
       [12.,  0.]])

In [191]:
WT

array([[25.,  0.],
       [27.,  0.],
       [27., 30.],
       [ 0., 28.],
       [ 0., 35.]])

In [197]:
#计算后验概率
phi = WT/(WT.sum(axis=0))
phi

array([[0.3164557 , 0.        ],
       [0.34177215, 0.        ],
       [0.34177215, 0.32258065],
       [0.        , 0.30107527],
       [0.        , 0.37634409]])

In [200]:
theta = DT/DT.sum(axis=0)
theta
#归一化
theta = theta/np.sum(theta,axis=1).reshape(16,1)
theta

array([[1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.12827586, 0.87172414],
       [0.06476323, 0.93523677],
       [0.        , 1.        ],
       [0.28181818, 0.71818182],
       [1.        , 0.        ],
       [0.22738386, 0.77261614],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.10532276, 0.89467724],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ]])

In [201]:
#对比原结果
np.argmax(theta,axis=1) == orig_topics

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])